version: 2

models:
  - name: stg_egx30 
    description: "البيانات النظيفة والموحدة لأسعار الأسهم اليومية (EGX30)"
    
    # 1. الاختبارات على مستوى الموديل (اللي نجحت)
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - stock_symbol
            - trade_date
            
    # 2. تعريف الأعمدة والاختبارات الفردية
    columns:
      
      - name: stock_symbol
        description: "رمز السهم"
        tests:
          - not_null       
      
      - name: trade_date
        description: "تاريخ التداول"
        tests:
          - not_null       

      - name: closing_price
        description: "سعر الإغلاق اليومي"
        tests:
          # استخدام accepted_range: (لازم تكون القيمة > 0)
          - dbt_utils.accepted_range:
              min_value: 0.0001 # أقل قيمة ممكنة هي قيمة موجبة جداً
              inclusive: true # القيمة دي مسموح بيها
          
      - name: volume
        description: "حجم التداول اليومي"
        tests:
          # استخدام accepted_range: (لازم تكون القيمة >= 0)
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true # القيمة صفر مسموح بيها في حجم التداول